dist: trusty
sudo: required
language: cpp

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9

  - compiler: clang
    addons:
      apt:
        packages:
        - 'clang-3.8'

os:
 - linux

script:
 - make
 - make test
